var productos;

productos=[
{//PC//
    nombre:"Age of Empires IV PC (DIGITAL)",
    imagen:"img/JUE2119D_2022112414538_f.jpg",
    precio:29.990,
    descripcion:"Uno de los juegos de estrategia en tiempo real más queridos vuelve a la carga con Age of Empires IV, una nueva entrega que te pondrá en el centro de épicas batallas históricas que transformaron el mundo, con formas nuevas y conocidas de expandir tu imperio en amplios paisajes con una increíble fidelidad visual en 4K.",
    plataforma:"PC",
    desarrollador:"Microsoft",
},
{
    nombre:"Star Wars: Jedi Fallen Order PC",
    imagen:"img/JUE2098_20191111124359_f.jpg",
    precio:19.990,
    descripcion:"Juego de un solo jugador con una historia en la que te metes en la piel de un Padawan Jedi que logró escapar de milagro de la purga de la Orden 66 luego de los acontecimientos del Episodio 3: La venganza de los Sith.",
    plataforma:"PC",
    desarrollador:"Electronic Arts",
},
{
    nombre:"Plants vs Zombies Battle for Neighborville PC",
    imagen:"img/JUE2104_2019926135223_f.jpg",
    precio:19.990,
    descripcion:"Únete a la nueva cosecha de esta milenaria batalla entre plantas y zombis con 20 clases totalmente personalizables en el lanzamiento, con una clase que se juega en equipo para cada facción. Lleva las habilidades únicas de cada clase de personaje a los seis modos JcJ, como la nueva Arena de batallas, y vive las emociones alucinantes de estos combates.",
    plataforma:"PC",
    desarrollador:"Electronic Arts",
},
{
    nombre:"FIFA 20 PC",
    imagen:"img/JUE2101_201992315552_f.jpg",
    precio:5.990,
    descripcion:"El fútbol vuelve a las calles con la auténtica cultura, la creatividad y el estilo de las pistas urbanas.",
    plataforma:"PC",
    desarrollador:"Electronic Arts",
},
{//PS4//
    nombre:"Fallout 4: Game of the Year Edition PS4",
    imagen:"img/PS4G0812_201781012578_f.jpg",
    precio:19.990,
    descripcion:"Explora. Lucha. Crea. Construye. En el mundo post-apocalíptico de Fallout 4, todas y cada una de tus acciones cambiará el mundo que te rodea, en la experiencia de rol definitiva en un mundo abierto.",
    plataforma:"PS4",
    desarrollador:"Bethesda",
},
{
    nombre:"Cuphead PS4",
    imagen:"img/PS4G1987_202326121133_f.jpg",
    precio:39.990,
    descripcion:"Cuphead es un juego de acción clásico de correr y disparar centrado especialmente en batallas con jefes. Inspirado en los dibujos animados de la década de 1930, los aspectos visuales y sonoros se han creado meticulosamente con las mismas técnicas de la época (es decir, animación tradicional en transparencias dibujadas a mano, fondos de acuarela y grabaciones de jazz originales).",
    plataforma:"PS4",
    desarrollador:"",
},
{
    nombre:"Power Rangers: Battle for the Grid Collector E PS4",
    imagen:"img/PS4G1988_202326122340_f.jpg",
    precio:19.990,
    descripcion:"En Power Rangers: Battle for the Grid, la última entrega de la serie que cuenta con 25 años a sus espaldas, disfrutarás de gráficos asombrosos y detalles realistas. Enfrenta a Rangers y villanos actuales y clásicos como nunca en batallas por equipos de 3 contra 3. Pon a prueba tus habilidades en línea contra amigos y jugadores de todos los rincones del mundo en una partida tras otras.",
    plataforma:"PS4",
    desarrollador:"Maximum",
},
{
    nombre:"Elden Ring (Euro) PS4",
    imagen:"img/PS4G1984_202312012249_f.jpg",
    precio:49.990,
    descripcion:"Viaja a través de las Tierras Intermedias, un nuevo mundo de fantasía creado por Hidetaka Miyazaki, creador de la influyente serie de videojuegos DARK SOULS, y George RR Martin, autor de la serie de fantasía más vendida del New York Times, A Song of Ice and Fire. Desentraña los misterios del poder del Anillo de Elden.",
    plataforma:"PS4",
    desarrollador:"Bandai Namco",
},
{//XB360//
    nombre:"Tales from the Borderlands XBOX 360",
    imagen:"img/XB360G1386_2016224164637_f.jpg",
    precio:6.990,
    descripcion:"Disfruta de una aventura al más puro estilo de TellTale Games, con el tradicional sistema de elección de diálogo y decisiones que hará que la historia en cada sesión de juego sea diferente según tus elecciones.",
    plataforma:"XB360",
    desarrollador:"2K",
},
{
    nombre:"Grand Theft Auto GTA San Andreas XBOX 360",
    imagen:"img/XB360G1363_202192313917_f.jpg",
    precio:19.990,
    descripcion:"Hace cinco años, Carl Johnson dejó atrás su vida en Los Santos, San Andreas, una ciudad consumida por las pandillas, las drogas y la corrupción. Estamos a principios de los noventa y Carl debe regresar. Su madre fue asesinada, su familia se rompe en pedazos y sus amigos de la infancia van camino al desastre. Además, un par de policías corruptos lo acusan de homicidio. CJ se ve arrastrado a un viaje por todo San Andreas para salvar a su familia y obtener el control de las calles.",
    plataforma:"XB360",
    desarrollador:"Rockstar Studios",
},
{
    nombre:"Metal Gear Solid V: Ground Zeroes XBOX 360",
    imagen:"img/XB360G1080_20131217165743_f.jpg",
    precio:9.990,
    descripcion:"Guía a Snake en una misión por salvar a sus aliados y sus soldados de una amenaza implacable surgida de las cenizas del pasado, en una aventura que hará que te cuestiones todo lo que creías saber de la saga creada por Hideo Kojima.",
    plataforma:"XB360",
    desarrollador:"Konami",
},
{
    nombre:"Portal 2 XBOX 360",
    imagen:"img/portal2x360.jpg",
    precio:19.990,
    descripcion:"El juego que redefinió tanto a los juegos de puzzles y los FPS regresa en una secuela más grande, más compleja y más demente que su predecesor, todo por cortesía de Aperture Science Laboratories",
    plataforma:"XB360",
    desarrollador:"Valve",
},
{//3DS//
    nombre:"Fire Emblem Warriors 3DS",
    imagen:"img/N3DSG0353_2017613144611_f.jpg",
    precio:29.990,
    descripcion:"Lucha contra legiones de fieros soldados y feroces monstruos en la piel de Marth, Xander, Corrin y otros héroes de Fire Emblem para desatar potentes y exorbitantes ataques al estilo Dynasty Warriors.",
    plataforma:"3DS",
    desarrollador:"Nintendo",
},
{
    nombre:"RPG Maker Fes 3DS",
    imagen:"img/N3DSG0354_20172209231_f.jpg",
    precio:27.990,
    descripcion:"Las sencillas pero potentes herramientas del juego te permiten insuflar vida a las historias nacidas de tu imaginación. Personaliza a personajes, historias, combates y muchas más cosas para convertirte en el próximo gran desarrollador. Luego podrás compartir tus creaciones y jugar con las de otros gracias a RPG Maker Player.",
    plataforma:"3DS",
    desarrollador:"NIS",
},
{
    nombre:"Runbow Pocket Deluxe Edition 3DS",
    imagen:"img/N3DSG0335_2017619131233_f.jpg",
    precio:19.990,
    descripcion:"Runbow lleva toda la diversión y el colorido caos de Runbow a la consola New Nintendo 3DS. Domina los modos Aventura, Bowhemoth y La aventura espacial de Satura, en solitario o con amigos a través del juego local. También es posible crear tarjetas StreetPass para compartir estadísticas divertidas con tus amigos.",
    plataforma:"3DS",
    desarrollador:"Nighthawk Interactive",
},
{
    nombre:"Sonic Boom: Fire & Ice 3DS",
    imagen:"img/N3DSG0274_201562212240_f.jpg",
    precio:17.990,
    descripcion:"El icónico erizo azul, Sonic the Hedgehog, correrá una vez más en Sonic Boom: Fire & Ice, un juego que introduce más aventura, velocidad, exploración y un nuevo elemento de jugabilidad de fuego y hielo que contribuirá a impulsar la acción. El juego también supone el retorno triunfal de Sonic, Tails, Knuckles, Amy y Sticks.",
    plataforma:"3DS",
    desarrollador:"Sega",
},
]